services:

  frontend:
    build: './frontend'
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
      - backend
    networks:
      - order_scheduler_network

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    env_file:
      - .env
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - order_scheduler_network
  
  backend:
    build: './backend'
    env_file:
      - .env
    user: nobody
    ports:
      - "5555:5555"
      - "5001:5001"
    depends_on:
      - rabbit
    networks:
      - order_scheduler_network


networks:
  order_scheduler_network:
    driver: bridge

